[Errno 24] Too many open files: b'/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/envs/s2e0/lib/python3.8/site-packages/tensorflow/include/external/mkl_dnn_v1/src/cpu/x64'
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1132, in __call__
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/mamba.py", line 941, in exception_converter
    raise e
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/mamba.py", line 934, in exception_converter
    exit_code = _wrapped_main(*args, **kwargs)
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/mamba.py", line 892, in _wrapped_main
    result = do_call(parsed_args, p)
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/mamba.py", line 754, in do_call
    exit_code = install(args, parser, "install")
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/mamba.py", line 599, in install
    handle_txn(conda_transaction, prefix, args, newenv)
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/linking.py", line 44, in handle_txn
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/core/link.py", line 283, in execute
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/core/link.py", line 765, in _execute
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/core/path_actions.py", line 1157, in cleanup
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/gateways/disk/delete.py", line 176, in rm_rf
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/gateways/disk/delete.py", line 148, in remove_empty_parent_paths
OSError: [Errno 24] Too many open files: b'/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/envs/s2e0/lib/python3.8/site-packages/tensorflow/include/external/mkl_dnn_v1/src/cpu/x64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/bin/mamba", line 11, in <module>
    sys.exit(main())
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/mamba/mamba.py", line 946, in main
    return conda_exception_handler(exception_converter, *args, **kwargs)
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1432, in conda_exception_handler
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1135, in __call__
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1175, in handle_exception
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1186, in handle_unexpected_exception
  File "/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1248, in print_unexpected_error_report
OSError: [Errno 24] Too many open files: '/afs/crc.nd.edu/user/k/kmealey2/miniforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main_info.py'